var swiper = new Swiper(".slide-content",{
    slidesPerView: 4,
    spaceBetween:25,
    slidesPerGroup:1,
    centerSlide:'true',
    fade:'true',
    grabCursor:'true',
    loop:true,
    loopFillGroupWithBlank:true,
    pagination:{
        el:".swiper-pagination",
        clickable:true,
        dynamicBullets:true,
    },
    navigation:{
        nextEl:".swiper-button-next",
        prevEl:".swiper-button-prev",
    },
    breakpoints:{
        0:{
            slidesPerView:1,
        },
        520:{
            slidesPerView:2,
        },
        920:{
            slidesPerView:3,
        },
        1280:{
            slidesPerView:4,
        },
        0:{
            slidesPerView:1,
        }
    }
});